fortran_compiler:          # [win]
  - flang                  # [win]
fortran_compiler_version:  # [win]
  - 20.1.8                 # [win]

c_compiler:                # [win]
  - clang                  # [win]
cxx_compiler:              # [win]
  - clang                  # [win]

c_compiler_version:
  - 20.1.8                 # [win]
  - 17                     # [osx]
cxx_compiler_version:
  - 20.1.8                 # [win]
  - 17                     # [osx]
